use_frameworks! # LeanCloud Swift SDK can only be integrated as framework.

target ‘ipad’ do
    pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
    pod 'AVOSCloudIM'             # 实时通信模块
    pod 'AVOSCloudCrashReporting' # 错误报告模块
    pod 'Alamofire','~> 4.4’
    pod 'BMPlayer'
  
    pod 'Reveal-SDK', :configurations => ['Debug']
    pod 'SwipeBack'                         ## 全能滑动手势返回,建议集成
end