use_frameworks! # LeanCloud Swift SDK can only be integrated as framework.

target ‘Miku’ do
    pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
    pod 'AVOSCloudIM'             # 实时通信模块
    pod 'AVOSCloudCrashReporting' # 错误报告模块
    pod 'Alamofire','~> 4.4’
end